# Generated by Django 4.2.1 on 2023-06-03 16:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('testeinoa', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Stocks',
            new_name='Stock',
        ),
    ]
